import { ClipboardItem, ClipboardType } from '../types';

// --- Colors ---
export const THEME_COLORS = {
  GOLD: '#D4AF37',
  BLACK: '#000000',
  WHITE: '#FFFFFF',
  DARK_GRAY: '#1A1A1A'
};

// --- Mock Data ---
export const INITIAL_CLIPBOARD_DATA: ClipboardItem[] = [
  {
    id: '1',
    content: 'Your paragraph tex buhuhuhuh jebuetguejjebuebgueugeutmmm',
    type: ClipboardType.TEXT,
    category: 'clipboard',
    timestamp: '10:44 PM • 20 Dec',
    tags: ['#work'],
    isPinned: true,
    isFavorite: true,
    isDeleted: false,
  },
  {
    id: '2',
    content: 'my credit card no is *******1234 with pin *****abc',
    displayContent: 'my credit card no is *******1234\nwith pin *****abc',
    type: ClipboardType.SECURE,
    category: 'clipboard',
    timestamp: '10:43 PM • 23 Dec',
    tags: ['#sport'],
    isPinned: false,
    isFavorite: true,
    isDeleted: false,
  },
  {
    id: '3',
    content: 'https://www.google.com',
    type: ClipboardType.LINK,
    category: 'clipboard',
    timestamp: '10:42 PM • 23 Dec',
    tags: ['#sport'],
    isPinned: false,
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: '4',
    content: '+99 9876543210',
    type: ClipboardType.PHONE,
    category: 'clipboard',
    timestamp: '10:42 PM • 23 Dec',
    tags: ['#sport'],
    isPinned: false,
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: '4b',
    content: 'contact@example.com',
    type: ClipboardType.EMAIL,
    category: 'clipboard',
    timestamp: '10:41 PM • 23 Dec',
    tags: ['#work'],
    isPinned: false,
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: '5',
    content: '33rd Street, Fifth Avenue, New York City, New York, United States',
    type: ClipboardType.LOCATION,
    category: 'clipboard',
    timestamp: '10:42 PM • 23 Dec',
    tags: ['#sport'],
    isPinned: false,
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: '6',
    content: 'Meeting notes: Discuss Q1 roadmap and budget allocation.',
    type: ClipboardType.TEXT,
    category: 'notes',
    timestamp: '09:00 AM • 24 Dec',
    tags: ['#work', '#notes'],
    isPinned: false,
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: '7',
    content: 'Grocery List:\n- Milk\n- Eggs\n- Bread\n- Coffee',
    title: 'Shopping',
    type: ClipboardType.TEXT,
    category: 'notes',
    timestamp: '06:30 PM • 24 Dec',
    tags: ['#personal', '#todo'],
    isPinned: true,
    isFavorite: false,
    isDeleted: false,
  }
];